// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srztqpnkchchbrdcnryx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyenRxcG5rY2hjaGJyZGNucnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODc2NzMsImV4cCI6MjA2OTg2MzY3M30.wLK2EAaapnd5IC-tMsiev7c6CiCrAaKA59ka0t_yFYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});